---
## Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.5.1
_src_path: gh:kc-workspace/asdf-plugin-template.git
addon_yaml:
    archive: false
    checksum: true
    download: true
    fetch: true
    git: false
    github: true
    gpg: true
    help: true
    install: true
    package: false
    python: false
    system: true
    tags: true
    version: false
app_desc: Command-line JSON processor
app_name: jq
app_repo: https://github.com/jqlang/jq
app_type: standalone
app_website: https://jqlang.github.io/jq/
archive_conf_path: ''
archive_conf_strip: 0
archive_enabled: true
archive_regex: (\\.tar\\.gz|\\.tgz|\\.zip)$
checksum_conf_algorithm: 256
checksum_enabled: true
checksum_url: https://github.com/jqlang/jq/raw/master/sig/v{version}/sha256sum.txt
custom_bin_paths: bin
custom_non_stable_version: (rc|-src|-dev|-latest|-stm|[-\.]rc|-alpha|-beta|[-\.]pre|-next|snapshot|master)
custom_require_commands: ''
download_url: https://github.com/jqlang/jq/releases/download/jq-{version}/jq-{os}-{arch}
gpg_enabled: true
gpg_public_key_email: no-send-email@jqlang.github.io
gpg_public_key_fingerprint: 93079A9511EFC0B7D6CDBFB5B0DA60FB454BAF18
gpg_public_key_keyid: ''
gpg_public_key_link: https://raw.githubusercontent.com/jqlang/jq/master/sig/jq-release-new.key
gpg_public_key_type: link
gpg_sig_url: https://github.com/jqlang/jq/raw/master/sig/v{version}/jq-{os}-{arch}.asc
install_map_enabled: true
install_map_method: move
install_map_yaml:
    jq: bin/jq
package_enabled: false
plugin_author: Kamontat Chantrachirathumrong
plugin_name: asdf-jq
plugin_org: kc-workspace
plugin_repo: https://github.com/kc-workspace/asdf-jq.git
source_enabled: false
sys_arch_enabled: true
sys_arch_yaml:
    aarch64*: arm64
    armv5*: armhf
    armv6*: armhf
    armv7*: armhf
    i386: i386
    i686: i386
    powerpc64le: powerpc
    ppc64le: ppc64el
    x86: amd64
    x86_64: amd64
sys_ext_enabled: false
sys_os_enabled: true
sys_os_yaml:
    darwin: macos
test_cmd_args: --version
version_file_enabled: false
version_prefix: jq-
